# Generated by Django 6.0.6 on 2026-07-16 16:38

import django.db.models.deletion
import laboratorio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_preencher_codigos_mv_conhecidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameLaboratorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('nome', models.CharField(max_length=180)),
                ('categoria', models.CharField(choices=[('bioquimica', 'Bioquímica'), ('hematologia', 'Hematologia'), ('microbiologia', 'Microbiologia'), ('imunologia', 'Imunologia'), ('urinanalise', 'Urinálise'), ('parasitologia', 'Parasitologia'), ('genetica', 'Genética'), ('outro', 'Outro')], max_length=30)),
                ('sinonimos', models.CharField(blank=True, help_text='Outros nomes usados na pesquisa.', max_length=255)),
                ('material', models.CharField(max_length=180)),
                ('recipiente', models.CharField(blank=True, help_text='Tubo ou recipiente indicado.', max_length=180)),
                ('volume_minimo', models.CharField(blank=True, max_length=80)),
                ('preparo', models.TextField(blank=True)),
                ('instrucoes_coleta', models.TextField(blank=True)),
                ('conservacao_transporte', models.TextField(blank=True)),
                ('prazo_resultado', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames_criados', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames_laboratoriais', to='usuarios.unidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=laboratorio.models.caminho_documento)),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(default='application/octet-stream', max_length=150)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='laboratorio.examelaboratorial')),
            ],
            options={
                'ordering': ['nome_original'],
            },
        ),
        migrations.AddConstraint(
            model_name='examelaboratorial',
            constraint=models.UniqueConstraint(fields=('unidade', 'nome'), name='exame_nome_unico_unidade'),
        ),
    ]
