# Generated by Django 6.0.6 on 2026-06-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='convenios.convenio')),
            ],
            options={
                'verbose_name': 'Plano do convênio',
                'verbose_name_plural': 'Planos dos convênios',
                'ordering': ['convenio__nome', 'nome'],
                'unique_together': {('convenio', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='RegraAtendimentoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento', models.CharField(choices=[('consulta', 'Consulta'), ('pronto_atendimento', 'Pronto Atendimento'), ('exame', 'Exame'), ('internacao', 'Internação'), ('cirurgia', 'Cirurgia'), ('terapia', 'Terapia'), ('pediatria', 'Pediatria')], max_length=40)),
                ('status', models.CharField(choices=[('aceito', 'Aceito'), ('nao_aceito', 'Não aceito'), ('consultar_autorizacao', 'Consultar autorização'), ('suspenso', 'Suspenso temporariamente')], default='aceito', max_length=40)),
                ('exige_autorizacao', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='convenios.convenio')),
                ('especialidade', models.ForeignKey(blank=True, help_text='Preencha quando a regra depender de especialidade. Ex: Ortopedia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras', to='convenios.especialidade')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='convenios.planoconvenio')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_convenios', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Regra de atendimento do convênio',
                'verbose_name_plural': 'Regras de atendimento dos convênios',
                'ordering': ['unidade__nome', 'convenio__nome', 'plano__nome', 'tipo_atendimento', 'especialidade__nome'],
            },
        ),
    ]
