# Generated by Django 6.0.6 on 2026-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoconvenio',
            options={'ordering': ['convenio__nome', 'nome', 'codigo_mv'], 'verbose_name': 'Plano do convênio', 'verbose_name_plural': 'Planos dos convênios'},
        ),
        migrations.AlterUniqueTogether(
            name='planoconvenio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='convenio',
            name='codigo_mv',
            field=models.CharField(blank=True, db_index=True, help_text='Código do convênio no MV.', max_length=30),
        ),
        migrations.AddField(
            model_name='convenio',
            name='tipo_mv',
            field=models.CharField(blank=True, help_text='Tipo informado no relatório do MV. Ex: CONVENIO, PARTICULAR.', max_length=80),
        ),
        migrations.AddField(
            model_name='planoconvenio',
            name='codigo_mv',
            field=models.CharField(blank=True, db_index=True, help_text='Código do plano no MV.', max_length=30),
        ),
        migrations.AddField(
            model_name='planoconvenio',
            name='indice_codigo_mv',
            field=models.CharField(blank=True, help_text='Código do índice no MV.', max_length=30),
        ),
        migrations.AddField(
            model_name='planoconvenio',
            name='indice_nome_mv',
            field=models.CharField(blank=True, help_text='Nome do índice no MV.', max_length=160),
        ),
        migrations.AddField(
            model_name='planoconvenio',
            name='regra_codigo_mv',
            field=models.CharField(blank=True, help_text='Código da regra no MV.', max_length=30),
        ),
        migrations.AddField(
            model_name='planoconvenio',
            name='regra_nome_mv',
            field=models.CharField(blank=True, help_text='Nome da regra no MV.', max_length=160),
        ),
    ]
