# Generated by Django 6.0.6 on 2026-06-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_alter_planoconvenio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoProibidoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_procedimento', models.CharField(db_index=True, max_length=30)),
                ('descricao_procedimento', models.CharField(db_index=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_proibidos', to='convenios.convenio')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_proibidos', to='convenios.planoconvenio')),
            ],
            options={
                'verbose_name': 'Procedimento proibido do plano',
                'verbose_name_plural': 'Procedimentos proibidos dos planos',
                'ordering': ['convenio__nome', 'plano__nome', 'descricao_procedimento'],
                'unique_together': {('plano', 'codigo_procedimento')},
            },
        ),
    ]
