# Generated by Django 6.0.6 on 2026-06-30 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0003_procedimentoproibidoplano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('convenios_planos', 'Convênios e planos'), ('procedimentos_proibidos', 'Procedimentos proibidos'), ('regras_atendimento', 'Regras de atendimento')], max_length=40)),
                ('arquivo', models.FileField(help_text='Arquivo CSV ou XLSX para importação.', upload_to='importacoes_mv/%Y/%m/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('concluida_com_erros', 'Concluída com erros'), ('erro', 'Erro')], default='pendente', max_length=30)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('total_sucesso', models.PositiveIntegerField(default=0)),
                ('total_erros', models.PositiveIntegerField(default=0)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_mv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação MV',
                'verbose_name_plural': 'Importações MV',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemImportacaoMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('ignorado', 'Ignorado')], max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='convenios.importacaomv')),
            ],
            options={
                'verbose_name': 'Item da importação MV',
                'verbose_name_plural': 'Itens da importação MV',
                'ordering': ['importacao', 'linha'],
            },
        ),
    ]
