# Generated by Django 6.0.6 on 2026-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0004_importacaomv_itemimportacaomv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoTUSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.CharField(db_index=True, max_length=20, unique=True)),
                ('descricao', models.CharField(db_index=True, max_length=300)),
                ('grupo', models.CharField(blank=True, db_index=True, max_length=160)),
                ('subgrupo', models.CharField(blank=True, max_length=160)),
                ('codigo_mv', models.CharField(blank=True, db_index=True, max_length=40)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procedimento TUSS',
                'verbose_name_plural': 'Procedimentos TUSS',
                'ordering': ['descricao', 'codigo_tuss'],
            },
        ),
    ]
