# Generated by Django 6.0.6 on 2026-07-13 19:33

from django.db import migrations, models


def vincular_existentes(apps, schema_editor):
    Convenio = apps.get_model('convenios', 'Convenio')
    Unidade = apps.get_model('usuarios', 'Unidade')
    unidades = list(Unidade.objects.all())
    for convenio in Convenio.objects.all():
        convenio.unidades.add(*unidades)


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0006_criar_modulo_tuss'),
        ('usuarios', '0003_unidade_codigo_mv'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='unidades',
            field=models.ManyToManyField(blank=True, related_name='convenios_mv', to='usuarios.unidade'),
        ),
        migrations.RunPython(vincular_existentes, migrations.RunPython.noop),
    ]
