# Generated by Django 6.0.6 on 2026-07-13 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0007_convenio_unidades'),
        ('usuarios', '0004_preencher_codigos_mv_conhecidos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='procedimentoproibidoplano',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='procedimentoproibidoplano',
            name='fim_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimentoproibidoplano',
            name='inicio_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimentoproibidoplano',
            name='tipo_atendimento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='procedimentoproibidoplano',
            name='tipo_proibicao',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='procedimentoproibidoplano',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_proibidos_mv', to='usuarios.unidade'),
        ),
        migrations.AddConstraint(
            model_name='procedimentoproibidoplano',
            constraint=models.UniqueConstraint(fields=('unidade', 'plano', 'codigo_procedimento'), name='unico_procedimento_proibido_unidade_plano'),
        ),
    ]
