# Generated by Django 6.0.6 on 2026-07-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0008_alter_procedimentoproibidoplano_unique_together_and_more'),
        ('usuarios', '0004_preencher_codigos_mv_conhecidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacaoMVExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='processando', max_length=20)),
                ('convenios', models.PositiveIntegerField(default=0)),
                ('planos', models.PositiveIntegerField(default=0)),
                ('regras', models.PositiveIntegerField(default=0)),
                ('procedimentos', models.PositiveIntegerField(default=0)),
                ('mensagem', models.TextField(blank=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sincronizacoes_mv', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Execução da sincronização MV',
                'verbose_name_plural': 'Execuções da sincronização MV',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['unidade', '-iniciado_em'], name='convenios_s_unidade_7c54b2_idx')],
            },
        ),
    ]
