"""
Django settings for intranet_gsf project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('GSF_DEBUG', 'false').strip().lower() in {'1', 'true', 'yes', 'on'}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('GSF_SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-apenas-desenvolvimento-local-trocar-em-producao'
    else:
        raise ImproperlyConfigured(
            'GSF_SECRET_KEY é obrigatória quando GSF_DEBUG não está habilitado.'
        )

# A carga do MV permanece desligada até a migração do banco local para uma
# solução adequada a operações longas. Os dados já importados continuam
# disponíveis para consulta.
MV_SYNC_ENABLED = os.environ.get('GSF_MV_SYNC_ENABLED', 'false').strip().lower() in {
    '1', 'true', 'yes', 'on',
}

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('GSF_ALLOWED_HOSTS', '').split(',') if host.strip()] or [
    "127.0.0.1",
    "localhost",
    "192.168.0.172",
    "intranet.osascohsf.hosp",
    "SRV-INTRANET",
    "SRV-INTRANET.osascohsf.hosp",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'usuarios',
    'modulos',
    'conteudos',
    'convenios',
    'status_sistemas',
    'ramais_contatos',
    'avisos',
    'documentos',
    'auditoria.apps.AuditoriaConfig',
    'solicitacoes_ti',
    'solicitacoes',
    'conversas',
    'base_conhecimento',
    'inventario_ti',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'usuarios.middleware.UnidadeAtivaMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'intranet_gsf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.contexto_usuario_gsf',
            ],
        },
    },
]

WSGI_APPLICATION = 'intranet_gsf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.environ.get('GSF_DB_ENGINE', 'sqlite').strip().lower()

if DB_ENGINE in {'postgres', 'postgresql'}:
    configuracao_postgres = {
        'NAME': os.environ.get('GSF_DB_NAME', '').strip(),
        'USER': os.environ.get('GSF_DB_USER', '').strip(),
        'PASSWORD': os.environ.get('GSF_DB_PASSWORD', ''),
        'HOST': os.environ.get('GSF_DB_HOST', '127.0.0.1').strip(),
        'PORT': os.environ.get('GSF_DB_PORT', '5432').strip(),
    }
    ausentes = [
        f'GSF_DB_{nome}'
        for nome in ('NAME', 'USER', 'PASSWORD')
        if not configuracao_postgres[nome]
    ]
    if ausentes:
        raise ImproperlyConfigured(
            'Configuração PostgreSQL incompleta: ' + ', '.join(ausentes)
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            **configuracao_postgres,
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {'connect_timeout': 10},
        }
    }
elif DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {'timeout': 60},
        }
    }
else:
    raise ImproperlyConfigured(
        'GSF_DB_ENGINE deve ser "sqlite" ou "postgresql".'
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG else
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
        )
    },
}

AUTH_USER_MODEL = 'usuarios.Usuario'

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Logging de operação
LOG_DIR = Path(os.environ.get('GSF_LOG_DIR', BASE_DIR / 'logs'))
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_LEVEL = os.environ.get('GSF_LOG_LEVEL', 'INFO').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} pid={process:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'application_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'gsf-hub.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 10,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'application_file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django.request': {
            'handlers': ['console', 'application_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['application_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
