# Generated by Django 6.0.6 on 2026-07-10 18:37

import conversas.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversas', '0002_grupos_conversas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=conversas.models.caminho_anexo_mensagem)),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(max_length=120)),
                ('tamanho', models.PositiveBigIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='conversas.mensagemchat')),
            ],
        ),
        migrations.CreateModel(
            name='StatusUsuarioChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_disponibilidade', models.CharField(choices=[('online', 'Disponível'), ('ausente', 'Ausente'), ('ocupado', 'Ocupado'), ('nao_perturbe', 'Não perturbe'), ('offline', 'Offline')], default='online', max_length=20)),
                ('ultima_atividade', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensagem_status', models.CharField(blank=True, max_length=160)),
                ('status_expira_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
