# Generated by Django 6.0.6 on 2026-06-26 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('avisos', 'Avisos / Comunicados'), ('documentos', 'Documentos / Protocolos ONA'), ('status_sistemas', 'Status dos Sistemas'), ('conteudos', 'Conteúdos / Manuais / Links'), ('ramais', 'Ramais e Contatos'), ('convenios', 'Convênios MV'), ('usuarios', 'Usuários'), ('sistema', 'Sistema'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('alterado', 'Alterado'), ('excluido', 'Excluído'), ('encerrado', 'Encerrado'), ('login', 'Login'), ('logout', 'Logout'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('titulo', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True)),
                ('modelo', models.CharField(blank=True, help_text='Nome técnico do model. Ex: AvisoComunicado.', max_length=120)),
                ('objeto_id', models.CharField(blank=True, help_text='ID do registro relacionado.', max_length=80)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to='usuarios.unidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
