# Generated by Django 6.0.6 on 2026-07-10 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Alerta'), ('danger', 'Crítica')], default='info', max_length=20)),
                ('icone', models.CharField(default='🔔', max_length=30)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=80)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'origem', 'objeto_id'), name='notificacao_unica_por_usuario_origem_objeto')],
            },
        ),
    ]
