# Generated by Django 6.0.6 on 2026-07-10 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('modulos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_usuarios', to='modulos.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_modulos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['modulo__ordem', 'modulo__nome'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'modulo'), name='favorito_modulo_unico_por_usuario')],
            },
        ),
    ]
