# Generated by Django 6.0.6 on 2026-07-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputadorInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=120, unique=True)),
                ('usuario', models.CharField(blank=True, default='-', max_length=180)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_local', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, default='-', max_length=50)),
                ('sistema', models.CharField(blank=True, default='-', max_length=180)),
                ('cpu', models.CharField(blank=True, default='-', max_length=255)),
                ('ram', models.CharField(blank=True, default='-', max_length=80)),
                ('disco_total', models.CharField(blank=True, default='-', max_length=80)),
                ('disco_livre', models.CharField(blank=True, default='-', max_length=80)),
                ('disco_percentual', models.CharField(blank=True, default='-', max_length=80)),
                ('fabricante', models.CharField(blank=True, default='-', max_length=180)),
                ('modelo', models.CharField(blank=True, default='-', max_length=180)),
                ('serial', models.CharField(blank=True, default='-', max_length=180)),
                ('patrimonio', models.CharField(blank=True, default='-', max_length=80)),
                ('agent_version', models.CharField(blank=True, default='-', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultimo_contato', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Inventário TI',
                'ordering': ['hostname'],
            },
        ),
    ]
