# Generated by Django 6.0.6 on 2026-07-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoComputadorInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cadastro', 'Cadastro'), ('alteracao', 'Alteração'), ('heartbeat', 'Heartbeat'), ('status', 'Status')], max_length=30)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('campo', models.CharField(blank=True, default='', max_length=80)),
                ('valor_anterior', models.TextField(blank=True, default='')),
                ('valor_novo', models.TextField(blank=True, default='')),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='inventario_ti.computadorinventario')),
            ],
            options={
                'verbose_name': 'Histórico do computador',
                'verbose_name_plural': 'Histórico do inventário TI',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['computador', '-criado_em'], name='inventario__computa_94e050_idx'), models.Index(fields=['tipo', '-criado_em'], name='inventario__tipo_5fc22b_idx')],
            },
        ),
    ]
