# Generated by Django 6.0.6 on 2026-07-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0002_historicocomputadorinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErroAgenteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=120)),
                ('agent_version', models.CharField(blank=True, default='-', max_length=50)),
                ('categoria', models.CharField(blank=True, default='geral', max_length=80)),
                ('mensagem', models.TextField()),
                ('detalhe', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('computador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_agente', to='inventario_ti.computadorinventario')),
            ],
            options={
                'verbose_name': 'Erro do agente',
                'verbose_name_plural': 'Erros dos agentes',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['hostname', '-criado_em'], name='inventario__hostnam_2c4150_idx'), models.Index(fields=['categoria', '-criado_em'], name='inventario__categor_4219e0_idx')],
            },
        ),
    ]
