# Generated by Django 6.0.6 on 2026-07-08 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0003_erroagenteinventario'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('computador', 'Computador'), ('notebook', 'Notebook'), ('monitor', 'Monitor'), ('impressora', 'Impressora'), ('nobreak', 'Nobreak'), ('rede', 'Rede'), ('periferico', 'Periférico'), ('outro', 'Outro')], default='computador', max_length=30)),
                ('status', models.CharField(choices=[('em_uso', 'Em uso'), ('estoque', 'Estoque'), ('manutencao', 'Manutenção'), ('baixado', 'Baixado'), ('extraviado', 'Extraviado')], default='em_uso', max_length=30)),
                ('responsavel', models.CharField(blank=True, default='', max_length=180)),
                ('fabricante', models.CharField(blank=True, default='', max_length=180)),
                ('modelo', models.CharField(blank=True, default='', max_length=180)),
                ('serial', models.CharField(blank=True, default='', max_length=180)),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=120)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('computador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_vinculado', to='inventario_ti.computadorinventario')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.setor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Patrimônio TI',
                'verbose_name_plural': 'Patrimônios TI',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoPatrimonioTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cadastro', 'Cadastro'), ('transferencia', 'Transferência'), ('manutencao', 'Manutenção'), ('baixa', 'Baixa'), ('retorno', 'Retorno'), ('ajuste', 'Ajuste')], max_length=30)),
                ('responsavel_origem', models.CharField(blank=True, default='', max_length=180)),
                ('responsavel_destino', models.CharField(blank=True, default='', max_length=180)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('setor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimonio_destino', to='usuarios.setor')),
                ('setor_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimonio_origem', to='usuarios.setor')),
                ('unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimonio_destino', to='usuarios.unidade')),
                ('unidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimonio_origem', to='usuarios.unidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='inventario_ti.patrimonioti')),
            ],
            options={
                'verbose_name': 'Movimentação de patrimônio TI',
                'verbose_name_plural': 'Movimentações de patrimônio TI',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='patrimonioti',
            index=models.Index(fields=['codigo'], name='inventario__codigo_46b14b_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimonioti',
            index=models.Index(fields=['tipo', 'status'], name='inventario__tipo_570bf3_idx'),
        ),
    ]
