# Generated by Django 6.0.6 on 2026-07-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0004_patrimonioti_movimentacaopatrimonioti_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadorinventario',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.unidade'),
        ),
        migrations.AddField(
            model_name='erroagenteinventario',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.unidade'),
        ),
        migrations.AlterField(
            model_name='computadorinventario',
            name='hostname',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='computadorinventario',
            constraint=models.UniqueConstraint(fields=('unidade', 'hostname'), name='uniq_computador_unidade_hostname'),
        ),
    ]
