# Generated by Django 6.0.6 on 2026-07-13 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0005_computadorinventario_unidade_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressoraMonitorada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('modelo_informado', models.CharField(blank=True, default='', max_length=180)),
                ('modelo_detectado', models.CharField(blank=True, default='', max_length=180)),
                ('local', models.CharField(max_length=180)),
                ('ativo', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=False)),
                ('status_dispositivo', models.CharField(blank=True, default='', max_length=255)),
                ('toner_percentual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cilindro_percentual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('ultima_consulta', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Impressora monitorada',
                'verbose_name_plural': 'Impressoras monitoradas',
                'ordering': ['local', 'ip'],
                'indexes': [models.Index(fields=['unidade', 'ativo', 'online'], name='inventario__unidade_acefe3_idx')],
            },
        ),
    ]
