# Generated by Django 6.0.6 on 2026-07-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0006_impressoramonitorada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoramentoActiveDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlador', models.CharField(max_length=255, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('ldap_ok', models.BooleanField(default=False)),
                ('kerberos_ok', models.BooleanField(default=False)),
                ('dns_ok', models.BooleanField(default=False)),
                ('smb_ok', models.BooleanField(default=False)),
                ('latencia_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('ultima_consulta', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitoramento do Active Directory',
                'verbose_name_plural': 'Monitoramentos do Active Directory',
                'ordering': ['controlador'],
            },
        ),
    ]
