# Generated by Django 6.0.6 on 2026-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0007_monitoramentoactivedirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoramentoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cpu_percentual', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('memoria_percentual', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('memoria_total_gb', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('disco_percentual', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('disco_livre_gb', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('uptime_segundos', models.PositiveBigIntegerField(default=0)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('ultima_consulta', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitoramento do servidor',
                'verbose_name_plural': 'Monitoramentos dos servidores',
                'ordering': ['hostname'],
            },
        ),
    ]
