# Generated by Django 6.0.6 on 2026-07-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0008_monitoramentoservidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoramentoRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Rede HSFOS', max_length=120, unique=True)),
                ('gateway_ip', models.GenericIPAddressField(default='192.168.0.1')),
                ('gateway_ok', models.BooleanField(default=False)),
                ('dns_ip', models.GenericIPAddressField(default='192.168.0.30')),
                ('dns_ok', models.BooleanField(default=False)),
                ('switch_ip', models.GenericIPAddressField(default='192.168.0.53')),
                ('switch_ok', models.BooleanField(default=False)),
                ('switch_modelo', models.CharField(blank=True, default='', max_length=255)),
                ('switch_uptime_segundos', models.PositiveBigIntegerField(default=0)),
                ('switch_interfaces', models.PositiveIntegerField(default=0)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('ultima_consulta', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitoramento de rede',
                'verbose_name_plural': 'Monitoramentos de rede',
            },
        ),
    ]
