# Generated by Django 6.0.6 on 2026-07-13 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0009_monitoramentorede'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuprimentoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80)),
                ('nome', models.CharField(max_length=180)),
                ('categoria', models.CharField(choices=[('toner', 'Toner'), ('cilindro', 'Cilindro'), ('papel', 'Papel'), ('cabo', 'Cabo'), ('periferico', 'Periférico'), ('peca', 'Peça'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('fabricante', models.CharField(blank=True, default='', max_length=120)),
                ('modelo_compativel', models.CharField(blank=True, default='', max_length=180)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suprimentos_ti', to='usuarios.setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suprimentos_ti', to='usuarios.unidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoSuprimentoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo_anterior', models.PositiveIntegerField()),
                ('saldo_atual', models.PositiveIntegerField()),
                ('impressora_destino', models.CharField(blank=True, default='', max_length=180)),
                ('responsavel', models.CharField(blank=True, default='', max_length=180)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('setor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_suprimentos_ti', to='usuarios.setor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suprimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='inventario_ti.suprimentoti')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='suprimentoti',
            constraint=models.UniqueConstraint(fields=('unidade', 'setor', 'codigo'), name='uniq_suprimento_unidade_setor_codigo'),
        ),
    ]
