# Generated by Django 6.0.6 on 2026-07-13 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0010_suprimentoti_movimentacaosuprimentoti_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaosuprimentoti',
            name='estornada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaosuprimentoti',
            name='estornada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_suprimento_estornadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaosuprimentoti',
            name='motivo_estorno',
            field=models.TextField(blank=True, default=''),
        ),
    ]
