# Generated by Django 6.0.6 on 2026-07-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0011_movimentacaosuprimentoti_estornada_em_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='suprimentoti',
            name='uniq_suprimento_unidade_setor_codigo',
        ),
        migrations.AlterField(
            model_name='suprimentoti',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suprimentos_ti', to='usuarios.setor'),
        ),
        migrations.AddConstraint(
            model_name='suprimentoti',
            constraint=models.UniqueConstraint(fields=('unidade', 'codigo'), name='uniq_suprimento_unidade_codigo'),
        ),
    ]
