# Generated by Django 6.0.6 on 2026-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0012_remove_suprimentoti_uniq_suprimento_unidade_setor_codigo_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='suprimentoti',
            name='uniq_suprimento_unidade_codigo',
        ),
        migrations.AddField(
            model_name='suprimentoti',
            name='escopo',
            field=models.CharField(choices=[('ti', 'Tecnologia da Informação'), ('setorial', 'Estoque Setorial')], default='ti', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='suprimentoti',
            constraint=models.UniqueConstraint(fields=('unidade', 'setor', 'escopo', 'codigo'), name='uniq_suprimento_escopo_codigo'),
        ),
    ]
