# Generated by Django 6.0.6 on 2026-07-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0013_remove_suprimentoti_uniq_suprimento_unidade_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suprimentoti',
            name='categoria',
            field=models.CharField(max_length=80),
        ),
    ]
