# Generated by Django 6.0.6 on 2026-07-14

import core.services.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('inventario_ti', '0014_alter_suprimentoti_categoria')]

    operations = [
        migrations.CreateModel(
            name='AnexoMovimentacaoSuprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.services.uploads.caminho_upload)),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(default='application/octet-stream', max_length=150)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='inventario_ti.movimentacaosuprimentoti')),
            ],
            options={
                'verbose_name': 'Anexo da movimentação de suprimento',
                'verbose_name_plural': 'Anexos das movimentações de suprimentos',
                'ordering': ['criado_em'],
            },
        ),
    ]
