# Generated by Django 6.0.6 on 2026-07-16 20:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_ti', '0018_custos_e_impressora_movimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraImpressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('status_dispositivo', models.CharField(blank=True, default='', max_length=255)),
                ('toner_percentual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cilindro_percentual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, default='')),
                ('coletado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='inventario_ti.impressoramonitorada')),
            ],
            options={
                'verbose_name': 'Leitura de impressora',
                'verbose_name_plural': 'Leituras de impressoras',
                'ordering': ['-coletado_em'],
                'indexes': [models.Index(fields=['impressora', '-coletado_em'], name='inventario__impress_7af61d_idx')],
            },
        ),
    ]
