# Generated by Django 6.0.6 on 2026-07-07 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('status', 'Status'), ('prioridade', 'Prioridade'), ('responsavel', 'Responsável'), ('comentario', 'Comentário'), ('atualizacao', 'Atualização'), ('conclusao', 'Conclusão')], max_length=30)),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('valor_anterior', models.CharField(blank=True, max_length=255)),
                ('valor_novo', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='solicitacoes.solicitacaointerna')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico da Solicitação',
                'verbose_name_plural': 'Históricos das Solicitações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
