# Generated by Django 6.0.6 on 2026-06-26 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('comunicado', 'Comunicado'), ('manutencao', 'Manutenção'), ('indisponibilidade', 'Indisponibilidade'), ('orientacao', 'Orientação'), ('mudanca_fluxo', 'Mudança de fluxo'), ('urgente', 'Urgente')], default='comunicado', max_length=40)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica')], default='normal', max_length=40)),
                ('resumo', models.CharField(blank=True, help_text='Resumo curto para aparecer no portal.', max_length=220)),
                ('mensagem', models.TextField(help_text='Mensagem completa do comunicado.')),
                ('link_externo', models.URLField(blank=True, help_text='Opcional: link relacionado ao aviso.')),
                ('arquivo', models.FileField(blank=True, help_text='Opcional: anexo relacionado ao comunicado.', null=True, upload_to='avisos/%Y/%m/')),
                ('fixar_no_topo', models.BooleanField(default=False, help_text='Avisos fixados aparecem primeiro.')),
                ('exibir_no_dashboard', models.BooleanField(default=True, help_text='Exibe este aviso na tela inicial do portal.')),
                ('ativo', models.BooleanField(default=True)),
                ('publicado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField(blank=True, help_text='Opcional. Após essa data, o aviso deixa de aparecer.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_criados', to=settings.AUTH_USER_MODEL)),
                ('grupos_permitidos', models.ManyToManyField(blank=True, help_text='Se não selecionar grupos, aparece para todos os usuários logados.', related_name='avisos_comunicados', to='auth.group')),
                ('unidade', models.ForeignKey(blank=True, help_text='Deixe em branco para comunicado geral, válido para todas as unidades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_comunicados', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Aviso / comunicado',
                'verbose_name_plural': 'Avisos / comunicados',
                'ordering': ['-fixar_no_topo', '-prioridade', '-publicado_em', 'titulo'],
            },
        ),
    ]
