# Generated by Django 6.0.6 on 2026-06-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisocomunicado',
            name='unidades_compartilhadas',
            field=models.ManyToManyField(blank=True, help_text='Use para compartilhar o aviso com outras unidades específicas.', related_name='avisos_compartilhados', to='usuarios.unidade'),
        ),
    ]
