# Generated by Django 6.0.6 on 2026-07-16 16:07

import django.db.models.deletion
import recursos_humanos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_preencher_codigos_mv_conhecidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('beneficios', 'Benefícios'), ('ferias', 'Férias'), ('declaracao', 'Declaração / documento'), ('folha_ponto', 'Folha ou ponto'), ('cadastro', 'Atualização cadastral'), ('afastamento', 'Afastamento'), ('outro', 'Outro assunto')], max_length=30)),
                ('assunto', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('aguardando', 'Aguardando solicitante'), ('concluida', 'Concluída'), ('indeferida', 'Indeferida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('resposta_rh', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_rh', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_rh', to='usuarios.setor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_rh', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_rh', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Solicitação de RH',
                'verbose_name_plural': 'Solicitações de RH',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='recursos_humanos.solicitacaorh')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=recursos_humanos.models.caminho_anexo)),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(default='application/octet-stream', max_length=150)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='recursos_humanos.solicitacaorh')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
