# Generated by Django 6.0.6 on 2026-07-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0004_preencher_codigos_mv_conhecidos'),
    ]
    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admissao', 'Admissão / novos acessos'), ('alteracao', 'Alteração de acesso'), ('mudanca_setor', 'Mudança de setor'), ('bloqueio', 'Bloqueio temporário'), ('desligamento', 'Desligamento / revogação')], max_length=30)),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('colaborador_nome', models.CharField(max_length=180)),
                ('colaborador_matricula', models.CharField(blank=True, max_length=60)),
                ('colaborador_cargo', models.CharField(blank=True, max_length=120)),
                ('sistemas', models.TextField(help_text='Informe um sistema ou acesso por linha.')),
                ('justificativa', models.TextField()),
                ('data_necessaria', models.DateField(blank=True, null=True)),
                ('observacao_ti', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_acesso_responsavel', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_acesso', to='usuarios.setor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_acesso_abertas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_acesso', to='usuarios.unidade')),
            ],
            options={'verbose_name': 'Solicitação de acesso', 'verbose_name_plural': 'Solicitações de acesso', 'ordering': ['-criado_em']},
        ),
        migrations.CreateModel(
            name='HistoricoSolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='gestao_acessos.solicitacaoacesso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-criado_em']},
        ),
    ]
