# Generated by Django 6.0.6 on 2026-06-26 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Ex: POP-TI-001, PROT-ENF-002.', max_length=60)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('pop', 'POP'), ('protocolo', 'Protocolo'), ('politica', 'Política interna'), ('norma', 'Norma'), ('manual', 'Manual'), ('formulario', 'Formulário'), ('fluxo', 'Fluxo'), ('outro', 'Outro')], default='pop', max_length=40)),
                ('categoria', models.CharField(choices=[('assistencial', 'Assistencial'), ('administrativo', 'Administrativo'), ('qualidade', 'Qualidade / ONA'), ('ti', 'Tecnologia da Informação'), ('operacional', 'Operacional'), ('rh', 'Recursos Humanos'), ('financeiro', 'Financeiro'), ('outro', 'Outro')], default='assistencial', max_length=40)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(help_text='Anexe o documento em PDF, DOCX, XLSX ou outro formato permitido.', upload_to='documentos/%Y/%m/')),
                ('versao', models.CharField(blank=True, help_text='Ex: 1.0, 2.1, revisão 03.', max_length=30)),
                ('responsavel', models.CharField(blank=True, help_text='Responsável pelo documento.', max_length=160)),
                ('data_publicacao', models.DateField(default=django.utils.timezone.localdate)),
                ('data_validade', models.DateField(blank=True, help_text='Opcional. Usado para controle de vencimento.', null=True)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('em_revisao', 'Em revisão'), ('vencido', 'Vencido'), ('inativo', 'Inativo')], default='vigente', max_length=40)),
                ('exibir_no_dashboard', models.BooleanField(default=False, help_text='Exibe no dashboard quando estiver próximo do vencimento ou em revisão.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_criados', to=settings.AUTH_USER_MODEL)),
                ('grupos_permitidos', models.ManyToManyField(blank=True, help_text='Se não selecionar grupos, aparece para todos os usuários logados.', related_name='documentos_protocolos', to='auth.group')),
                ('setor', models.ForeignKey(blank=True, help_text='Opcional. Use para vincular o documento a um setor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_protocolos', to='usuarios.setor')),
                ('unidade', models.ForeignKey(blank=True, help_text='Deixe em branco para documento geral, válido para todas as unidades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_protocolos', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Documento / Protocolo',
                'verbose_name_plural': 'Documentos / Protocolos',
                'ordering': ['categoria', 'tipo', 'titulo'],
            },
        ),
    ]
