# Generated by Django 6.0.6 on 2026-06-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoprotocolo',
            name='leitura_obrigatoria',
            field=models.BooleanField(default=False, help_text='Reservado para controle futuro de leitura obrigatória.'),
        ),
        migrations.AddField(
            model_name='documentoprotocolo',
            name='unidades_compartilhadas',
            field=models.ManyToManyField(blank=True, help_text='Use para compartilhar o documento com outras unidades específicas.', related_name='documentos_compartilhados', to='usuarios.unidade'),
        ),
        migrations.AlterField(
            model_name='documentoprotocolo',
            name='categoria',
            field=models.CharField(choices=[('assistencial', 'Assistencial'), ('administrativo', 'Administrativo'), ('qualidade', 'Qualidade / ONA'), ('ti', 'Tecnologia da Informação'), ('operacional', 'Operacional'), ('rh', 'Recursos Humanos'), ('financeiro', 'Financeiro'), ('farmacia', 'Farmácia'), ('enfermagem', 'Enfermagem'), ('corpo_clinico', 'Corpo Clínico'), ('outro', 'Outro')], default='assistencial', max_length=40),
        ),
        migrations.AlterField(
            model_name='documentoprotocolo',
            name='status',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('em_revisao', 'Em revisão'), ('vencido', 'Vencido'), ('obsoleto', 'Obsoleto'), ('substituido', 'Substituído'), ('inativo', 'Inativo')], default='vigente', max_length=40),
        ),
        migrations.AlterField(
            model_name='documentoprotocolo',
            name='tipo',
            field=models.CharField(choices=[('pop', 'POP'), ('protocolo', 'Protocolo'), ('politica', 'Política interna'), ('norma', 'Norma'), ('manual', 'Manual'), ('formulario', 'Formulário'), ('fluxo', 'Fluxo'), ('plano_contingencia', 'Plano de contingência'), ('documento_institucional', 'Documento institucional'), ('outro', 'Outro')], default='pop', max_length=40),
        ),
    ]
