# Generated by Django 6.0.6 on 2026-07-01 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria da base de conhecimento',
                'verbose_name_plural': 'Categorias da base de conhecimento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('pop', 'POP'), ('manual', 'Manual'), ('orientacao', 'Orientação'), ('politica', 'Política'), ('fluxo', 'Fluxo'), ('treinamento', 'Treinamento'), ('outro', 'Outro')], default='pop', max_length=40)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='base_conhecimento/%Y/%m/')),
                ('link_externo', models.URLField(blank=True)),
                ('versao', models.CharField(blank=True, default='1.0', max_length=30)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('em_revisao', 'Em revisão'), ('obsoleto', 'Obsoleto'), ('rascunho', 'Rascunho')], default='vigente', max_length=30)),
                ('leitura_obrigatoria', models.BooleanField(default=False)),
                ('data_revisao', models.DateField(blank=True, help_text='Data prevista ou realizada da revisão.', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_conhecimento_atualizados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='base_conhecimento.categoriaconhecimento')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_conhecimento_criados', to=settings.AUTH_USER_MODEL)),
                ('grupos_permitidos', models.ManyToManyField(blank=True, related_name='documentos_conhecimento_permitidos', to='auth.group')),
                ('responsavel_revisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisao', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, help_text='Deixe em branco para disponibilizar para todos os setores.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_conhecimento', to='usuarios.setor')),
                ('unidade', models.ForeignKey(blank=True, help_text='Deixe em branco para disponibilizar para todas as unidades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_conhecimento', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Documento da base de conhecimento',
                'verbose_name_plural': 'Documentos da base de conhecimento',
                'ordering': ['ordem', 'categoria__nome', 'setor__nome', 'titulo'],
            },
        ),
    ]
