# Generated by Django 6.0.6 on 2026-07-01 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraDocumentoConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_documento', models.CharField(blank=True, max_length=30)),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='base_conhecimento.documentoconhecimento')),
                ('setor_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras_base_conhecimento', to='usuarios.setor')),
                ('unidade_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras_base_conhecimento', to='usuarios.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_documentos_conhecimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmação de leitura',
                'verbose_name_plural': 'Confirmações de leitura',
                'ordering': ['-confirmado_em'],
                'unique_together': {('documento', 'usuario', 'versao_documento')},
            },
        ),
    ]
