# Generated by Django 6.0.6 on 2026-06-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamalContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('setor', 'Setor'), ('pessoa', 'Pessoa'), ('servico', 'Serviço'), ('emergencia', 'Emergência / Crítico')], default='setor', max_length=30)),
                ('setor', models.CharField(blank=True, help_text='Ex: TI, Recepção, Faturamento, Centro Cirúrgico.', max_length=120)),
                ('nome', models.CharField(help_text='Nome do setor, pessoa ou serviço.', max_length=160)),
                ('cargo_funcao', models.CharField(blank=True, help_text='Ex: Coordenador, Analista, Recepção, Plantão.', max_length=120)),
                ('ramal', models.CharField(blank=True, max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('celular', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('localizacao', models.CharField(blank=True, help_text='Ex: 1º andar, Recepção principal, Sala TI.', max_length=160)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('unidade', models.ForeignKey(blank=True, help_text='Deixe em branco para contato geral, válido para todas as unidades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ramais_contatos', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Ramal e contato',
                'verbose_name_plural': 'Ramais e contatos',
                'ordering': ['unidade__nome', 'setor', 'ordem', 'nome'],
            },
        ),
    ]
