# Generated by Django 6.0.6 on 2026-06-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais_contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramalcontato',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Informe somente se for diferente do celular.', max_length=40),
        ),
    ]
