# Generated by Django 6.0.6 on 2026-07-13 18:31

from django.db import migrations, models


def copiar_unidade_atual(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    through = Usuario.unidades_permitidas.through
    vinculos = [
        through(usuario_id=usuario.id, unidade_id=usuario.unidade_id)
        for usuario in Usuario.objects.exclude(unidade_id__isnull=True).iterator()
    ]
    through.objects.bulk_create(vinculos, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='unidades_permitidas',
            field=models.ManyToManyField(blank=True, help_text='Empresas/unidades que o usuário pode selecionar durante o uso da intranet.', related_name='usuarios_autorizados', to='usuarios.unidade'),
        ),
        migrations.RunPython(copiar_unidade_atual, migrations.RunPython.noop),
    ]
