# Generated by Django 6.0.6 on 2026-07-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_unidades_permitidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='codigo_mv',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Código da empresa no MV'),
        ),
    ]
