# Generated by Django 6.0.6 on 2026-06-26 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Resumo curto da solicitação.', max_length=180)),
                ('tipo', models.CharField(choices=[('acesso', 'Acesso / Permissão'), ('sistema', 'Sistema'), ('mv', 'MV / Sistema Hospitalar'), ('pep', 'PEP / Prontuário Eletrônico'), ('idce', 'IDCE / Laudos'), ('impressora', 'Impressora'), ('rede', 'Rede / Internet / Wi-Fi'), ('ramal', 'Ramal / Telefonia'), ('equipamento', 'Equipamento'), ('email', 'E-mail'), ('outro', 'Outro')], default='outro', max_length=40)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica')], default='normal', max_length=40)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('aguardando_usuario', 'Aguardando usuário'), ('aguardando_terceiro', 'Aguardando terceiro'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='aberto', max_length=40)),
                ('descricao', models.TextField(help_text='Descreva a necessidade, erro ou solicitação.')),
                ('equipamento', models.CharField(blank=True, help_text='Opcional. Ex: computador, impressora, ramal, setor, IP ou patrimônio.', max_length=160)),
                ('anexo', models.FileField(blank=True, help_text='Opcional. Print, documento ou evidência da solicitação.', null=True, upload_to='solicitacoes_ti/%Y/%m/')),
                ('resposta_ti', models.TextField(blank=True, help_text='Resposta, tratativa ou solução aplicada pela TI.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('responsavel_ti', models.ForeignKey(blank=True, help_text='Responsável da TI pelo atendimento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_ti_responsavel', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_ti', to='usuarios.setor')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_ti_abertas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_ti', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Solicitação interna de TI',
                'verbose_name_plural': 'Solicitações internas de TI',
                'ordering': ['-criado_em'],
            },
        ),
    ]
