# Generated by Django 6.0.6 on 2026-06-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_ti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoti',
            name='conversa_iniciada',
            field=models.BooleanField(default=False, help_text='Somente após a TI iniciar a conversa o solicitante poderá responder.'),
        ),
        migrations.AddField(
            model_name='solicitacaoti',
            name='conversa_iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoti',
            name='visto_pela_ti',
            field=models.BooleanField(default=False, help_text='Indica se a solicitação já foi visualizada pela TI.'),
        ),
        migrations.AddField(
            model_name='solicitacaoti',
            name='visto_pela_ti_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
