# Generated by Django 6.0.6 on 2026-06-26 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_ti', '0002_solicitacaoti_conversa_iniciada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoti',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='solicitacoes_ti/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='solicitacaoti',
            name='conversa_iniciada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitacaoti',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solicitacaoti',
            name='equipamento',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='solicitacaoti',
            name='responsavel_ti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_ti_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacaoti',
            name='resposta_ti',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitacaoti',
            name='titulo',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='solicitacaoti',
            name='visto_pela_ti',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MensagemSolicitacaoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('ti', 'TI'), ('solicitante', 'Solicitante'), ('sistema', 'Sistema')], default='sistema', max_length=30)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lida_pela_ti', models.BooleanField(default=False)),
                ('lida_pelo_solicitante', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_solicitacoes_ti', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='solicitacoes_ti.solicitacaoti')),
            ],
            options={
                'verbose_name': 'Mensagem da solicitação de TI',
                'verbose_name_plural': 'Mensagens das solicitações de TI',
                'ordering': ['criado_em'],
            },
        ),
    ]
