# Generated by Django 6.0.6 on 2026-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_ti', '0003_alter_solicitacaoti_anexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoti',
            name='sla_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Prazo de SLA em horas, calculado pela prioridade.', null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoti',
            name='sla_prazo_em',
            field=models.DateTimeField(blank=True, help_text='Data e hora limite para atendimento conforme SLA.', null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoti',
            name='sla_status',
            field=models.CharField(choices=[('dentro_prazo', 'Dentro do prazo'), ('proximo_vencimento', 'Próximo do vencimento'), ('estourado', 'SLA estourado'), ('encerrado', 'Encerrado'), ('sem_sla', 'Sem SLA')], default='sem_sla', max_length=40),
        ),
    ]
