# Generated by Django 6.0.6 on 2026-07-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_ti', '0004_solicitacaoti_sla_horas_solicitacaoti_sla_prazo_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoti',
            name='modulo_origem',
            field=models.CharField(choices=[('portal', 'Portal'), ('mv', 'MV / Sistema Hospitalar'), ('base_conhecimento', 'Base de Conhecimento'), ('documentos', 'Documentos / Protocolos'), ('manuais', 'Manuais e Procedimentos'), ('avisos', 'Avisos / Comunicados'), ('ramais', 'Ramais e Contatos'), ('status_sistemas', 'Status dos Sistemas'), ('conversas', 'Conversas Internas'), ('administracao', 'Administração da Intranet'), ('outros', 'Outros')], default='portal', help_text='Módulo da intranet onde o chamado foi aberto.', max_length=60),
        ),
    ]
