# Generated by Django 6.0.6 on 2026-06-25 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('modulos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('convenio', 'Convênio'), ('contingencia', 'Contingência'), ('link', 'Link útil'), ('chamado', 'Chamado externo'), ('observacao', 'Observação')], max_length=30)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, help_text='Use para PDF, DOCX, XLSX ou arquivos internos.', null=True, upload_to='conteudos/%Y/%m/')),
                ('link_externo', models.URLField(blank=True, help_text='Use para links externos ou sistemas internos.')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupos_permitidos', models.ManyToManyField(blank=True, help_text='Se não selecionar nenhum grupo, aparece para todos os usuários com acesso ao módulo.', related_name='conteudos_permitidos', to='auth.group')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='modulos.modulo')),
                ('unidade', models.ForeignKey(blank=True, help_text='Deixe em branco para aparecer para todas as unidades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudos', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Conteúdo do módulo',
                'verbose_name_plural': 'Conteúdos dos módulos',
                'ordering': ['tipo', 'ordem', 'titulo'],
            },
        ),
    ]
