# Generated by Django 6.0.6 on 2026-07-16 15:53

import acesso_remoto.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_preencher_codigos_mv_conhecidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcessoRemoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('vinculo', models.CharField(choices=[('colaborador', 'Colaborador'), ('medico', 'Médico / corpo clínico'), ('terceiro', 'Terceiro / fornecedor')], max_length=20)),
                ('empresa_terceira', models.CharField(blank=True, max_length=180)),
                ('tipo_acesso', models.CharField(choices=[('vpn', 'VPN'), ('remoto', 'Acesso remoto assistido'), ('ambos', 'VPN e acesso remoto')], max_length=20)),
                ('equipamento', models.CharField(help_text='Patrimônio ou identificação do equipamento.', max_length=180)),
                ('sistema_destino', models.CharField(help_text='Sistemas ou equipamentos que serão acessados.', max_length=255)),
                ('finalidade', models.TextField()),
                ('inicio_validade', models.DateTimeField()),
                ('fim_validade', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('em_configuracao', 'Em configuração'), ('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='pendente', max_length=30)),
                ('observacao_ti', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_vpn_atendidas', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_vpn', to='usuarios.setor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_vpn_abertas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_vpn', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Solicitação de acesso remoto',
                'verbose_name_plural': 'Solicitações de acesso remoto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAcessoRemoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=30)),
                ('status_novo', models.CharField(max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='acesso_remoto.solicitacaoacessoremoto')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoAcessoRemoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=acesso_remoto.models.caminho_anexo)),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(default='application/octet-stream', max_length=150)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='acesso_remoto.solicitacaoacessoremoto')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
