# Generated by Django 6.0.6 on 2026-07-16 16:26

import django.db.models.deletion
import financeiro_faturamento.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_preencher_codigos_mv_conhecidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('financeiro', 'Financeiro'), ('faturamento', 'Faturamento')], max_length=20)),
                ('tipo', models.CharField(choices=[('contas_pagar', 'Contas a pagar'), ('contas_receber', 'Contas a receber'), ('fechamento', 'Fechamento de competência'), ('recurso_glosa', 'Recurso de glosa'), ('envio_conta', 'Envio de conta'), ('conciliacao', 'Conciliação'), ('documentacao', 'Documentação'), ('outro', 'Outro')], max_length=30)),
                ('titulo', models.CharField(max_length=180)),
                ('competencia', models.DateField(help_text='Utilize o primeiro dia do mês de referência.')),
                ('prazo', models.DateField(blank=True, null=True)),
                ('entidade', models.CharField(blank=True, help_text='Convênio, fornecedor ou cliente relacionado.', max_length=180)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica')], default='normal', max_length=15)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('aguardando', 'Aguardando retorno'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('descricao', models.TextField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_financeiros_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_financeiros_responsavel', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_financeiros', to='usuarios.unidade')),
            ],
            options={
                'verbose_name': 'Registro financeiro/faturamento',
                'verbose_name_plural': 'Registros financeiros/faturamento',
                'ordering': ['-competencia', 'prazo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='financeiro_faturamento.registrofinanceiro')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=financeiro_faturamento.models.caminho_anexo)),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(default='application/octet-stream', max_length=150)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='financeiro_faturamento.registrofinanceiro')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
