# Generated by Django 6.0.6 on 2026-06-25 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaMonitorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('categoria', models.CharField(choices=[('assistencial', 'Assistencial'), ('administrativo', 'Administrativo'), ('infraestrutura', 'Infraestrutura'), ('terceiro', 'Fornecedor / Terceiro')], max_length=30)),
                ('icone', models.CharField(default='🖥️', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sistema monitorado',
                'verbose_name_plural': 'Sistemas monitorados',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('operacional', 'Operacional'), ('instavel', 'Instável'), ('indisponivel', 'Indisponível'), ('manutencao', 'Manutenção')], default='operacional', max_length=30)),
                ('impacto', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='baixo', max_length=30)),
                ('titulo', models.CharField(max_length=160)),
                ('mensagem', models.TextField(blank=True, help_text='Mensagem que será exibida aos usuários no portal.')),
                ('previsao', models.CharField(blank=True, help_text='Ex: Sem previsão, Em acompanhamento, Previsão 14h.', max_length=120)),
                ('acao_ti', models.TextField(blank=True, help_text='Informação interna da TI sobre a atuação.')),
                ('ativo', models.BooleanField(default=True, help_text='Somente ocorrências ativas aparecem no portal.')),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('unidade', models.ForeignKey(blank=True, help_text='Deixe em branco para ocorrência geral, válida para todas as unidades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_sistemas', to='usuarios.unidade')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='status_sistemas.sistemamonitorado')),
            ],
            options={
                'verbose_name': 'Ocorrência de sistema',
                'verbose_name_plural': 'Ocorrências de sistemas',
                'ordering': ['-ativo', '-atualizado_em'],
            },
        ),
    ]
