# Generated by Django 6.0.6 on 2026-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_sistemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciasistema',
            name='causa_raiz',
            field=models.TextField(blank=True, help_text='Causa raiz identificada no encerramento da ocorrência.'),
        ),
        migrations.AddField(
            model_name='ocorrenciasistema',
            name='observacao_encerramento',
            field=models.TextField(blank=True, help_text='Observação final do encerramento.'),
        ),
        migrations.AddField(
            model_name='ocorrenciasistema',
            name='solucao_aplicada',
            field=models.TextField(blank=True, help_text='Solução aplicada para normalização do ambiente.'),
        ),
    ]
