# Generated by Django 6.0.6 on 2026-06-30 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_sistemas', '0002_ocorrenciasistema_causa_raiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemamonitorado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sistemamonitorado',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
