# Generated by Django 6.0.6 on 2026-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('categoria', models.CharField(choices=[('assistencial', 'Sistemas assistenciais'), ('administrativo', 'Administrativo e documentos'), ('tecnologia', 'Tecnologia e acessos'), ('gestao', 'Gestão')], max_length=30)),
                ('icone', models.CharField(default='📁', max_length=10)),
                ('tag', models.CharField(blank=True, max_length=30)),
                ('link', models.CharField(default='#', max_length=255)),
                ('palavras_chave', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupos_permitidos', models.ManyToManyField(blank=True, help_text='Se não selecionar nenhum grupo, o módulo aparece para todos os usuários logados.', related_name='modulos_permitidos', to='auth.group')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['categoria', 'ordem', 'nome'],
            },
        ),
    ]
